### ISSUE TITLE
Add option to ignore certain files when inlining

### ISSUE THREAD

**Issue by carrotdonut** [pbakaus/grunt-cruncher#3]
Right now for my project, I am using the `inlineEverything` task to inline css stylesheets. However, I only want one of the stylesheets inlined, and the other to just keep the link tag in the html file. Could you add another option called `filesIgnore`, for example, which takes an array of file names to ignore when inlining? I would also be happy to create a PR to implement this change.

**Comment by pbakaus** [comment]
hi Kelly, seems like a reasonable request! I don't have bandwidth to do this myself, but I'd happily accept a PR if you create one. Thanks!

**Comment by carrotdonut** [comment]
Great! I'll create a PR soon then!

**Comment by carrotdonut** [comment]
@pbakaus Sorry I actually just found out our project's already using a fork of your grunt-cruncher, so I won't be needing to make a PR to this repo. But thank you for replying so fast!
